language: python

python:
  - 2.4
  - 2.6
  - 2.7
  - pypy
  - 3.1
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO_VERSION=1.4.21
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.9
  - DJANGO_VERSION=1.8.3
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
script:
  - env PYTHONPATH=`pwd` nosetests
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.21
    - python: "3.3"
      env: DJANGO_VERSION=1.4.21
    - python: "3.2"
      env: DJANGO_VERSION=1.4.21
    - python: "2.6"
      env: DJANGO_VERSION=1.7.9
    - python: "2.6"
      env: DJANGO_VERSION=1.8.3
